class PagesController < ApplicationController
  
  # controller for pages, not used for this project, generated by rails
  
  def welcome
  end

  def recommendation
    @gradings = Grading.all
  end

end
